/*
 * role-overlay-vitess-etcd-bootstrap.tf -- Phase 0.O
 *
 * One-shot: render /etc/nexus-etcd/etcd.conf.yml on the 3 vitess-etcd nodes,
 * write /etc/nexus-etcd/endpoints, start nexus-etcd.service in PARALLEL across
 * all 3 (raft needs simultaneous startup for the first `initial-cluster-state:
 * new` bootstrap), wait for leader election, verify an mTLS put/get round-trip.
 *
 * Descendant of the 0.G.4 patroni etcd-bootstrap, with one deliberate
 * difference: FULL mTLS (client-transport-security client-cert-auth: true).
 * Patroni used TLS-for-encryption + HTTP basic-auth RBAC; Vitess's topo client
 * authenticates with a client cert (vitess-server PKI role has client EKU), so
 * mTLS IS the access control -- no etcd RBAC username/password to manage.
 *
 * All etcd traffic (peer raft :2380 + client :2379) rides the VMnet10 backplane
 * by IP, so topo clients dial https://<vmnet10>:2379 (matching the cert IP-SAN)
 * and we avoid the bare-hostname self-dial trap (0.G.4 transient #8) entirely.
 *
 * Selective ops: var.enable_etcd_bootstrap. Pre-req: vitess_tls rendered
 * tls/{server-cert,server-key,ca}.pem on each etcd node.
 */

locals {
  # initial-cluster string: peers ride VMnet10 :2380 (node name = hostname).
  vitess_etcd_initial_cluster = join(",", [
    for host, m in local.etcd_nodes : "${host}=https://${m.vmnet10}:2380"
  ])
  # Client endpoints used by topo clients + the on-node nexus-etcdctl wrapper:
  # VMnet10 backplane :2379 (matches cert IP-SAN; no hostname self-dial).
  vitess_etcd_client_endpoints = local.etcd_endpoints
}

resource "null_resource" "vitess_etcd_bootstrap" {
  count = var.enable_etcd_bootstrap ? 1 : 0

  triggers = {
    tls_ids          = join(",", [for host in keys(local.etcd_nodes) : null_resource.vitess_tls[host].id])
    members          = local.vitess_etcd_initial_cluster
    etcd_bootstrap_v = "1" # v1 (0.O) = 3-member raft, full mTLS (client-cert-auth), no RBAC (cert is the auth).
  }

  depends_on = [null_resource.vitess_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser     = '${var.vitess_node_user}'
      $sshOpts     = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $endpoints   = '${local.vitess_etcd_client_endpoints}'
      $initCluster = '${local.vitess_etcd_initial_cluster}'
      $timeoutMin  = ${var.vitess_cluster_timeout_minutes}

      $members = @(
%{for host, m in local.etcd_nodes~}
        @{ Host='${host}'; VmIp='${m.vmnet11}'; PeerIp='${m.vmnet10}' },
%{endfor~}
        $null
      ) | Where-Object { $_ -ne $null }

      Write-Host "[vitess-etcd] $($members.Count) members; initial-cluster=$initCluster; client endpoints=$endpoints"

      # ─── Stage 1: render etcd.conf.yml + endpoints + enable nexus-etcd ─────
      foreach ($m in $members) {
        $configBody = @"
# Generated by role-overlay-vitess-etcd-bootstrap.tf -- Phase 0.O
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.
name: $($m.Host)
data-dir: /var/lib/nexus-etcd
listen-peer-urls: https://$($m.PeerIp):2380
listen-client-urls: https://$($m.PeerIp):2379,https://$($m.VmIp):2379,https://127.0.0.1:2379
initial-advertise-peer-urls: https://$($m.PeerIp):2380
advertise-client-urls: https://$($m.PeerIp):2379
initial-cluster: $initCluster
initial-cluster-token: nexus-vitess-etcd
initial-cluster-state: new
peer-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: true
client-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: true
auto-compaction-mode: periodic
auto-compaction-retention: "1"
quota-backend-bytes: 2147483648
"@
        $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

        $stage = @"
set -euo pipefail
echo '$configB64' | base64 -d | sudo tee /etc/nexus-etcd/etcd.conf.yml > /dev/null
sudo chown root:etcd /etc/nexus-etcd/etcd.conf.yml
sudo chmod 0640 /etc/nexus-etcd/etcd.conf.yml

echo '$endpoints' | sudo tee /etc/nexus-etcd/endpoints > /dev/null
sudo chown root:etcd /etc/nexus-etcd/endpoints
sudo chmod 0644 /etc/nexus-etcd/endpoints

sudo systemctl daemon-reload
sudo systemctl enable nexus-etcd.service
echo CONFIG_OK
"@
        $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
        $out = (ssh @sshOpts "$sshUser@$($m.VmIp)" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String).Trim()
        if ($out -notmatch 'CONFIG_OK') {
          throw "[vitess-etcd] $($m.Host): etcd.conf.yml staging failed -- $out"
        }
        Write-Host "[vitess-etcd] $($m.Host): config rendered + service enabled"
      }

      # Start all 3 in parallel (raft needs simultaneous start for fresh bootstrap).
      Write-Host "[vitess-etcd] starting nexus-etcd.service on all $($members.Count) members in parallel..."
      $members | ForEach-Object -ThrottleLimit 3 -Parallel {
        $m = $_
        $opts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
        # reset-failed clears any start-limit hit from a prior failed attempt
        # (e.g. certs not yet present) so the fresh start isn't refused.
        ssh @opts "$using:sshUser@$($m.VmIp)" "sudo systemctl reset-failed nexus-etcd.service 2>/dev/null; sudo systemctl start nexus-etcd.service" 2>&1 | Out-Null
      }

      # ─── Stage 2: wait for leader election ─────────────────────────────────
      Write-Host "[vitess-etcd] waiting for cluster leader election..."
      $deadline      = (Get-Date).AddMinutes($timeoutMin)
      $leaderId      = $null
      $rbacHostIndex = $null
      while ((Get-Date) -lt $deadline) {
        for ($i = 0; $i -lt $members.Count; $i++) {
          $m = $members[$i]
          $probe = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo /usr/local/sbin/nexus-etcdctl endpoint status --write-out=json 2>/dev/null" 2>&1 | Out-String).Trim()
          if ($probe -match '"leader":\s*([1-9][0-9]*)') {
            $leaderId      = $matches[1]
            $rbacHostIndex = $i
            break
          }
        }
        if ($leaderId) { break }
        Start-Sleep -Seconds 5
      }
      if (-not $leaderId) {
        foreach ($m in $members) {
          $j = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo journalctl -u nexus-etcd.service --no-pager -n 30" 2>&1 | Out-String)
          Write-Host "--- journal $($m.Host) ---"
          Write-Host $j
        }
        throw "[vitess-etcd] no leader elected within $timeoutMin min"
      }
      Write-Host "[vitess-etcd] cluster has elected a leader (member_id=$leaderId; observed from $($members[$rbacHostIndex].Host))"

      # ─── Stage 3: mTLS put/get round-trip verify ──────────────────────────
      $probeMember = $members[$rbacHostIndex]
      $verifyStage = @'
set -euo pipefail
sudo /usr/local/sbin/nexus-etcdctl put /nexus/vitess-etcd-bootstrap/marker "$(date -u +%FT%TZ)" >/dev/null
VAL=$(sudo /usr/local/sbin/nexus-etcdctl get /nexus/vitess-etcd-bootstrap/marker --print-value-only)
if [ -z "$VAL" ]; then
  echo "[vitess-etcd verify] ERROR: put-then-get round-trip returned empty" >&2
  exit 1
fi
echo "[vitess-etcd verify] mTLS put-then-get round-trip OK (value=$VAL)"
'@
      $verifyB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($verifyStage))
      $verifyOut = (ssh @sshOpts "$sshUser@$($probeMember.VmIp)" "echo '$verifyB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $verifyOut.Trim()
        throw "[vitess-etcd] post-bootstrap verify failed (rc=$LASTEXITCODE)"
      }
      Write-Host $verifyOut.Trim()

      Write-Host "[vitess-etcd] cluster ready: $($members.Count) members, full mTLS, topo endpoints=$endpoints"
    PWSH
  }
}
